{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "document-platform.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "document-platform.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.tls.certManagerIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.certManagerIssuer }}
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ default (printf "%s-tls" (include "document-platform.fullname" .)) .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "document-platform.fullname" . }}-web
                port:
                  name: http
{{- end }}
