apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "document-platform.fullname" . }}-mermaid
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "document-platform.labels" . | nindent 4 }}
    {{- include "document-platform.mermaid.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mermaid.replicaCount }}
  selector:
    matchLabels:
      {{- include "document-platform.mermaid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "document-platform.mermaid.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: mermaid
          image: "{{ .Values.image.mermaid.repository }}:{{ .Values.image.mermaid.tag }}"
          imagePullPolicy: {{ .Values.image.mermaid.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.mermaid.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
