{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "document-platform.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "document-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  NEXTAUTH_SECRET: {{ .Values.secrets.nextauthSecret | quote }}
  {{- if .Values.secrets.googleClientId }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | quote }}
  {{- end }}
{{- end }}
